rtm_dbt_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 8123
      user: default
      password: default_password
      database: analytics
      schema: analytics
